services:
  app:
    build: .
    ports:
      - "8000:8000" # Change port to 8000
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/url_shortener
      # Update the BASE_URL with your load balancer or local address
      - BASE_URL=http://localhost:8000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules # For Node, remove this. For Python, a similar bind mount might be needed for packages if you're developing, but often isn't needed.
    networks:
      - url-shortener-network

  mongodb:
    image: mongo:6.0
    container_name: url_shortner_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - url-shortener-network

  postgres:
    image: postgres:15
    container_name: url_shortner_postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - url-shortener-network
    restart: unless-stopped

  redis:
    image: redis:7.0
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_redis_password
    volumes:
      - redis-data:/data
    networks:
      - url-shortener-network
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres-data:
  redis-data:

networks:
  url-shortener-network:
    driver: bridge